### ISSUE TITLE
missing requirements.txt

### ISSUE THREAD

**Issue by sophia-wright-blue** [Naman-ntc/Action-Recognition#1]
the README asks to 'Kindly use the requirements.txt to set up your machine for replicating this experiment'. but I don't see a requirements.txt file, can you please upload it or point me to the file? thanks,

**Comment by udion** [comment]
@sophia-wright-blue 

you can use the one available here https://github.com/udion/pose2action

**Comment by sophia-wright-blue** [comment]
thank you for the quick response!
